permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Tyrael 
#  github: http://github.com/lay1010
#  music: http://site.douban.com/linanya
#linkedin: https://cn.linkedin.com/in/tyraelwang

# 站点信息
title: 活着真好
description: 享受生命之美好，感叹山峦之秀美；以我点滴之热忱,温暖冷漠之炎凉。
url: http://blog.bao3.org
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-33330683-3
  url: blog.bao3.org

# disqus 设置
disqus:
  shortname: bao3

# 主题设置，自动激活某个标签
active: Geek

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
